package com.sam.notai.views;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author sam
 */
import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLightLaf;
public class PrincipalPanel extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalPanel
     */
    public PrincipalPanel() {
        initComponents();
        AbaNotasPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PrincipalPanel = new javax.swing.JPanel();
        WindowOptionsPanel = new javax.swing.JPanel();
        SeparatorPanel = new javax.swing.JPanel();
        criarPrimeiraAbaButton = new javax.swing.JButton();
        AreaNotasPanel = new javax.swing.JLayeredPane();
        AbaNotasPanel = new javax.swing.JTabbedPane();
        abaNotasPanel1 = new com.sam.notai.views.AbaNotasPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(null);

        WindowOptionsPanel.setToolTipText("");

        javax.swing.GroupLayout WindowOptionsPanelLayout = new javax.swing.GroupLayout(WindowOptionsPanel);
        WindowOptionsPanel.setLayout(WindowOptionsPanelLayout);
        WindowOptionsPanelLayout.setHorizontalGroup(
            WindowOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        WindowOptionsPanelLayout.setVerticalGroup(
            WindowOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        criarPrimeiraAbaButton.setIcon(new javax.swing.ImageIcon("/home/sam/Desktop/Projects/notai/resources/icons/views/circle-plus.png")); // NOI18N
        criarPrimeiraAbaButton.setBorderPainted(false);
        criarPrimeiraAbaButton.setContentAreaFilled(false);
        criarPrimeiraAbaButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        criarPrimeiraAbaButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        criarPrimeiraAbaButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                criarPrimeiraAbaButtonKeyPressed(evt);
            }
        });

        AbaNotasPanel.addTab("tab1", abaNotasPanel1);

        jButton1.setText("jButton1");

        AreaNotasPanel.setLayer(AbaNotasPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        AreaNotasPanel.setLayer(jButton1, javax.swing.JLayeredPane.PALETTE_LAYER);

        javax.swing.GroupLayout AreaNotasPanelLayout = new javax.swing.GroupLayout(AreaNotasPanel);
        AreaNotasPanel.setLayout(AreaNotasPanelLayout);
        AreaNotasPanelLayout.setHorizontalGroup(
            AreaNotasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AbaNotasPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
            .addGroup(AreaNotasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(AreaNotasPanelLayout.createSequentialGroup()
                    .addGap(65, 65, 65)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(351, Short.MAX_VALUE)))
        );
        AreaNotasPanelLayout.setVerticalGroup(
            AreaNotasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AreaNotasPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(AbaNotasPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 681, Short.MAX_VALUE))
            .addGroup(AreaNotasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(AreaNotasPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jButton1)
                    .addContainerGap(652, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout SeparatorPanelLayout = new javax.swing.GroupLayout(SeparatorPanel);
        SeparatorPanel.setLayout(SeparatorPanelLayout);
        SeparatorPanelLayout.setHorizontalGroup(
            SeparatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SeparatorPanelLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(criarPrimeiraAbaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(162, 162, 162))
            .addGroup(SeparatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(AreaNotasPanel))
        );
        SeparatorPanelLayout.setVerticalGroup(
            SeparatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SeparatorPanelLayout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(criarPrimeiraAbaButton)
                .addContainerGap(277, Short.MAX_VALUE))
            .addGroup(SeparatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(AreaNotasPanel, javax.swing.GroupLayout.Alignment.TRAILING))
        );

        javax.swing.GroupLayout PrincipalPanelLayout = new javax.swing.GroupLayout(PrincipalPanel);
        PrincipalPanel.setLayout(PrincipalPanelLayout);
        PrincipalPanelLayout.setHorizontalGroup(
            PrincipalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(WindowOptionsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(SeparatorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PrincipalPanelLayout.setVerticalGroup(
            PrincipalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrincipalPanelLayout.createSequentialGroup()
                .addComponent(WindowOptionsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(SeparatorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PrincipalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PrincipalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void criarPrimeiraAbaButtonKeyPressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_criarPrimeiraAbaButtonKeyPressed
        criarPrimeiraAbaButton.setVisible(false);
        criarPrimeiraAbaButton.setEnabled(false);
        AbaNotasPanel.setVisible(true);
    }//GEN-LAST:event_criarPrimeiraAbaButtonKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            javax.swing.UIManager.setLookAndFeel(new FlatDarkLaf());
        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane AbaNotasPanel;
    private javax.swing.JLayeredPane AreaNotasPanel;
    private javax.swing.JPanel PrincipalPanel;
    private javax.swing.JPanel SeparatorPanel;
    private javax.swing.JPanel WindowOptionsPanel;
    private com.sam.notai.views.AbaNotasPanel abaNotasPanel1;
    private javax.swing.JButton criarPrimeiraAbaButton;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
